{% set version = "0.2.0" %}

package:
  name: vale-styles-readability
  version: {{ version }}

source:
  - folder: Readability
    fn: vale-Readability-0.1.1.zip
    url: https://github.com/errata-ai/Readability/releases/download/v{{ version }}/Readability.zip
    sha256: cf8790677bb2ef86458c1d1dbd6e646fd8063c0e9621f81141e5cd85e5e41f81
  - fn: LICENSE-vale-Readability-0.1.1
    url: https://raw.githubusercontent.com/errata-ai/Readability/v{{ version }}/LICENSE
    sha256: aa431e1653f927cf92be0fcc77fe388b97780b5f0f541085e30c4abe626b1074

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/Readability
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Readability rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
