{% set version = "0.1.1" %}

package:
  name: vale-styles-readability
  version: {{ version }}

source:
  - folder: Readability
    fn: vale-Readability-0.1.1.zip
    url: https://github.com/errata-ai/Readability/releases/download/v{{ version }}/Readability.zip
    sha256: fbe178b4b648c4d41bb72cee533addfd8f51cf0f3d1f0adfa08808770b418106
  - fn: LICENSE-vale-Readability-0.1.1
    url: https://raw.githubusercontent.com/errata-ai/Readability/v{{ version }}/LICENSE
    sha256: 087db0d367d5a1495d23e40e7029bee65226b20907f60887f1b53fd8e8e54f35

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/Readability
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Readability rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
